openai_api_key: your-openai-api-key-here
obisidian_directory: ../obsidian/
persistence_directory: ./vectordb
use_chat_model: False
openai_model: text-curie-001
temperature: 0.5
prompt: |
  # You are an interface for a personal Obsidian notebook.
  # You are asked a question by a user, and you must answer it using the information in the notebook.
  # you will be given access to relevant parts of the notebook.
  # You will be given a question and a context. You may add additional context if you wish.
  # If you don't know the answer, just say that you don't know, don't try to make up an answer.
  # You will be scored based on how many questions you answer correctly.
  # Use the following pieces of context to answer the question at the end.
  # {context}
  # Question: {question}